BOTONES = [{'ES':'Jugar','EN':'Play','BR':'Jogar'},
           {'ES':'Puntajes','EN':'Scores','BR':'Pontuações'},
           {'ES':'Salir','EN':'Exit','BR':'Sair'},
           {'ES':'Idioma:','EN':'Language:','BR':'Linguagem'},
           {'ES':'ES','EN':'EN','BR':'BR'},
           {'ES':'Puntaje:','EN':'Score:','BR':'Pontuações'},
           {'ES':'Letra:','EN':'Letter:','BR':'Letra:'},
           {'ES':'Errores:','EN':'Mistakes:','BR':'Erros'},
           {'ES':'Ganaste!','EN':'You win!','BR':'Você ganho!'},
           {'ES':'Perdiste!','EN':'You lose!','BR':'Você perdeu!'},
           {'ES':'El','EN':'The','BR':'O'},
           {'ES':'Ahorcado','EN':'Hangman','BR':'Carrasco'},
           {'ES':'Juego terminado','EN':'Game over','BR':'Fim de jogo'},
           {'ES':'Ingrese nombre:','EN':'Enter name:','BR':'Escreva seu nome'}]